create sequence tb_tweets_seq start with 1 increment by 50;
create table tb_roles (role_id bigint generated by default as identity, name varchar(255), primary key (role_id));
create table tb_tweets (creation_timestamp timestamp(6) with time zone, tweet_id bigint not null, user_id uuid, content varchar(255), primary key (tweet_id));
create table tb_users (user_id uuid not null, password varchar(255), user_name varchar(255) unique, primary key (user_id));
create table tb_users_roles (role_id bigint not null, user_id uuid not null, primary key (role_id, user_id));
alter table if exists tb_tweets add constraint FK8igcgf9ddaocdlg9c8scf01vm foreign key (user_id) references tb_users;
alter table if exists tb_users_roles add constraint FKj5qged12p22eloqw5g4f9hm2e foreign key (role_id) references tb_roles;
alter table if exists tb_users_roles add constraint FK5xc4yvfrjcy8bl01kq3crp8pg foreign key (user_id) references tb_users;
